version: "3.5"
services:
  sql-server-db:
    container_name: "sql_server_name"
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"


  app:
    image: aspcorecrud:v1
    build:
      context: .
      dockerfile: .
    container_name: "aspcorecrud_name"
    ports : 
      - "8080:80"
    depends_on:
      - sql-server-db

  frontend:
    image: angularfront_name
    build:
      context: "../angularFront/HW3angular/."
      dockerfile: "../angularFront/HW3angular/Dockerfile"
    ports : 
      - "4200:80"



networks:
  default:
    external:
      name: sql-server-test


